language: c

cache:
  apt: true

os:
  - linux

dist: trusty

addons:
  apt:
    sources:
      - sourceline: ppa:saltmakrell/ppa
    packages:
      - make
      - iverilog
      - yosys

env:
  matrix:
    - SYNTH=
    - SYNTH=`which yosys`

before_script:
  - make --no-print-directory

script:
  - make --no-print-directory --keep-going test
