language: c

cache:
  apt: true

os:
  - linux

dist: trusty

addons:
  apt:
    sources:
      - sourceline: ppa:saltmakrell/ppa
    packages:
      - make
      - iverilog
      - yosys

env:
  - SYNTH=
  - SYNTH=synth_

before_script:
  - make --no-print-directory ${SYNTH}build

script:
  - make --no-print-directory --keep-going ${SYNTH}test
