language: c

cache:
  apt: true

os:
  - linux

dist: trusty

addons:
  apt:
    sources:
      - sourceline: ppa:saltmakrell/ppa
    packages:
      - make
      - iverilog
      - yosys

before_script:
  - make SYNTH=`which yosys` --no-print-directory

script:
  - make SYNTH=`which yosys` --no-print-directory --keep-going test
