language: c

cache:
  apt: true

os:
  - linux

dist: trusty

addons:
  apt:
    sources:
      - sourceline: ppa:saltmakrell/ppa
    packages:
      - make
      - iverilog
      - yosys

env:
  - SYNTH_KW=
  - SYNTH_KW=synth_

before_script:
  - make --no-print-directory ${SYNTH_KW}build

script:
  - make --no-print-directory --keep-going ${SYNTH_KW}test
